# Generated by Django 4.2.11 on 2025-01-17 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 17, 9, 55, 36, 334536, tzinfo=datetime.timezone.utc), verbose_name='Create at'),
        ),
    ]
