# Generated by Django 4.2.11 on 2025-01-17 10:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_account_create_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Create at'),
        ),
    ]
